import React from 'react';

interface DualNotesViewProps {
  userContent: string;
  aiContent: string;
  onUserContentChange: (newContent: string) => void;
  onSave: () => void;
  userPlaceholder: string;
  aiPlaceholder: string;
  title: string;
  noteType: 'character' | 'plot';
}

const DualNotesView: React.FC<DualNotesViewProps> = ({ 
  userContent, 
  aiContent, 
  onUserContentChange, 
  onSave, 
  userPlaceholder, 
  aiPlaceholder, 
  title,
  noteType
}) => {
  return (
    <div className="flex-1 flex flex-col p-4 md:p-6 bg-base dark:bg-dark-base">
        <div className="flex items-center justify-between mb-4">
            <h2 className="text-2xl font-bold text-text-primary dark:text-dark-text-primary">{title}</h2>
            <p className="text-sm text-text-secondary dark:text-dark-text-secondary">Changes are saved automatically when you switch tabs or stop typing.</p>
        </div>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-full">
          <div className="flex flex-col h-full">
            <h3 className="text-lg font-semibold text-text-primary dark:text-dark-text-primary mb-2">
              Your {noteType === 'character' ? 'Character' : 'Plot'} Notes
            </h3>
            <textarea
                value={userContent}
                onChange={(e) => onUserContentChange(e.target.value)}
                onBlur={onSave}
                placeholder={userPlaceholder}
                className="w-full h-full flex-1 bg-surface dark:bg-dark-surface p-4 rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-primary text-text-primary dark:text-dark-text-primary leading-relaxed"
            />
          </div>
          
          <div className="flex flex-col h-full">
            <h3 className="text-lg font-semibold text-text-primary dark:text-dark-text-primary mb-2">
              AI-Generated {noteType === 'character' ? 'Character' : 'Plot'} Notes
            </h3>
            <textarea
                value={aiContent}
                readOnly
                placeholder={aiPlaceholder}
                className="w-full h-full flex-1 bg-surface dark:bg-dark-surface p-4 rounded-lg resize-none text-text-primary dark:text-dark-text-primary leading-relaxed opacity-75"
            />
            <p className="text-xs text-text-secondary dark:text-dark-text-secondary mt-2">
              These notes are automatically generated by the AI based on your conversation. 
              You can copy content from here to your notes if you find it useful.
            </p>
          </div>
        </div>
    </div>
  );
};

export default DualNotesView;